# Generated by Django 4.1.3 on 2023-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='kategori',
        ),
        migrations.AddField(
            model_name='shop',
            name='kategoriler',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
