# Generated by Django 4.1.3 on 2023-05-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shop_kategori_shop_kategoriler'),
    ]

    operations = [
        migrations.CreateModel(
            name='sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('urunismi', models.CharField(max_length=50)),
                ('aciklama', models.TextField()),
                ('resimUrl', models.CharField(max_length=200)),
                ('fiyat', models.IntegerField()),
                ('fiyatbirim', models.CharField(max_length=10)),
            ],
        ),
    ]
