# Generated by Django 4.1.3 on 2023-06-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('urunismi', models.CharField(max_length=50)),
                ('resimUrl', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
            ],
        ),
    ]
